name: fstack_rider
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  http: ^0.13.5
  flutter_svg: ^1.1.0
  cloud_firestore: ^3.5.1
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^0.2.6
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  flutter_lints: ^2.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter




flutter:
  assets:
    - assets/img/
    - assets/svg/
  uses-material-design: true

